import { useEffect, useState } from "react";
import { useParams, useNavigate } from "react-router";
import { useAuth } from "../../context/AuthContext";
import { API_BASE_URL } from "../../libs/api";

export const CertificateScreen = () => {
  const { id } = useParams();
  const { token } = useAuth();
  const [dana, setDana] = useState<any>(null);
  const [settings, setSettings] = useState<Record<string, string>>({});
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string>("");
  const [lang, setLang] = useState<"en" | "si">("en");
  const navigate = useNavigate();

  const fetchSettings = async () => {
    try {
      const res = await fetch(`${API_BASE_URL}/settings`);
      if (res.ok) {
        const data = await res.json();
        setSettings(data);
      }
    } catch (e) {
      console.error("Error fetching settings for certificate", e);
    }
  };

  useEffect(() => {
    fetchSettings();
  }, []);


  useEffect(() => {
    const fetchDana = async () => {
      try {
        setLoading(true);
        setError("");
        
        let res = await fetch(`${API_BASE_URL}/dana/${id}`, {
          headers: token ? { Authorization: `Bearer ${token}` } : {}
        });
        
        if (res.ok) {
          const data = await res.json();
          setDana(data);
          setLoading(false);
          return;
        }

        if (token) {
          res = await fetch(`${API_BASE_URL}/dana/admin/all`, {
            headers: { Authorization: `Bearer ${token}` }
          });
          if (res.ok) {
            const data = await res.json();
            const found = data.find((d: any) => d.id === Number(id));
            if (found) {
              setDana(found);
              setLoading(false);
              return;
            }
          }
        }

        setError("Certificate not found.");
      } catch (e) {
        console.error("Error fetching dana for certificate", e);
        setError("Error loading certificate.");
      } finally {
        setLoading(false);
      }
    };

    if (id) {
      fetchDana();
    }
  }, [id, token]);

  if (loading) return <div className="p-10 text-center text-ink font-semibold">Loading Certificate...</div>;
  if (error || !dana) return <div className="p-10 text-center text-red-600 font-bold">{error || "Certificate not found."}</div>;

  const mealNameEn = dana.mealType === 'MORNING' ? 'Morning Meal (Heel Dana)' : dana.mealType === 'NOON' ? 'Midday Meal (Dawal Dana)' : 'Evening Refreshments (Gilampasa)';
  const mealNameSi = dana.mealType === 'MORNING' ? 'හීල් දානමය පුණ්‍යකර්මය (Morning Meal)' : dana.mealType === 'NOON' ? 'දවල් දානමය පුණ්‍යකර්මය (Midday Meal)' : 'ගිලන්පස පූජාව (Evening Refreshments)';

  const formatDonorDisplayEn = () => {
    if (!dana) return "";
    const rawName = dana.name ? dana.name.trim() : "";
    return `${rawName} and Family`;
  };

  const formatDonorDisplaySi = () => {
    if (!dana) return "";
    const rawName = dana.name ? dana.name.trim() : "";
    return `${rawName} ඇතුළු පවුලේ සැම`;
  };

  // Template custom strings with fallbacks
  const certTitleEn = settings.cert_title_en || "Official Certificate of Dana Offering";
  const certTitleSi = settings.cert_title_si || "පුණ්‍යානුමෝදනා ශ්‍රී සන්නස් පත්‍රය";
  const certOrgEn = settings.cert_org_en || "Sagaramati Buddhist Monastery & Pirivena";
  const certOrgSi = settings.cert_org_si || "සාගරමති පිරිවෙන් සංවර්ධන සභාව";
  const certOfferedEn = settings.cert_offered_en || "Offered to the Most Venerable Maha Sangha of Sagaramati Monastery,";
  const certOfferedSi = settings.cert_offered_si || "කන්දෙගම ඓතිහාසික ධනංජය රජමහා විහාරස්ථ සාගරමති පිරිවෙනේ නේවාසික මහා සංඝරත්නය උදෙසා,";
  const certAckEn = settings.cert_ack_en || "This certificate gratefully acknowledges the devout sponsorship of this sacred merit.";
  const certAckSi = settings.cert_ack_si || "මෙම ශ්‍රේෂ්ඨ මහඟු දානමය පුණ්‍යකර්මය සාදරයෙන් අනුමත කොට පින් අනුමෝදන් කරමු.";
  const certBlessingEn = settings.cert_blessing_en || "May all immense virtues generated by this noble deed of Dana be shared with you, your family, loved ones, and departed ancestors for their peaceful well-being.";
  const certBlessingSi = settings.cert_blessing_si || "මෙම උතුම් දානමය පින්කමෙන් රැස්කරගන්නා ලද සියලු මහා කුසල් සම්පත් ඔබතුමා ඇතුළු පවුලේ සැමටත්, ඤාති මිත්‍රාදීන්ටත්, පරලොවප්‍රාප්ත ඤාතීන්ටත් අනුමෝදන් වේවා!";
  const certStanzaEn = settings.cert_stanza_en || "May the blessings of the Noble Triple Gem grant you good health, prosperity, happiness, and ultimate peace of Nibbana!";
  const certStanzaSi = settings.cert_stanza_si || "තුනුරුවනේ අනන්ත ගුණ බලයෙන් ඔබ සැමට දීර්ඝායුෂ, නීරෝගීභාවය, සාමය, සතුට හා උතුම් චතුරාර්ය සත්‍ය අවබෝධ වේවා!";
  const certSigEn = settings.cert_footer_sig_en || "With the blessings of the Venerable Sangha";
  const certSigSi = settings.cert_footer_sig_si || "ගෞරවනීය මහා සංඝරත්නයේ ආශීර්වාදයෙන්";

  return (
    <div className="bg-gray-100 min-h-screen py-10 px-4 flex flex-col items-center justify-center print:bg-white print:p-0">
      {/* Top Controls Bar */}
      <div className="mb-6 flex flex-wrap items-center justify-center gap-3 print:hidden">
        <button
          onClick={() => navigate(-1)}
          className="px-5 py-2.5 bg-gray-200 hover:bg-gray-300 text-ink font-bold text-xs rounded-xl shadow-sm transition-colors"
        >
          Back
        </button>

        {/* Language Selection Buttons */}
        <div className="flex bg-white p-1 rounded-xl shadow-sm border border-amber-300/80">
          <button
            onClick={() => setLang("en")}
            className={`px-4 py-2 text-xs font-bold rounded-lg transition-all ${
              lang === "en"
                ? "bg-brand-1 text-white shadow-md"
                : "text-gray-600 hover:text-ink hover:bg-gray-100"
            }`}
          >
            English Certificate
          </button>
          <button
            onClick={() => setLang("si")}
            className={`px-4 py-2 text-xs font-bold rounded-lg transition-all ${
              lang === "si"
                ? "bg-brand-1 text-white shadow-md"
                : "text-gray-600 hover:text-ink hover:bg-gray-100"
            }`}
          >
            සිංහල සහතිකය (Sinhala)
          </button>
        </div>

        <button
          onClick={() => window.print()}
          className="px-6 py-2.5 bg-emerald-700 hover:bg-emerald-800 text-white font-bold text-xs rounded-xl shadow-md transition-all"
        >
          Print / Download PDF
        </button>
      </div>

      {/* Certificate Card */}
      <div 
        className="bg-white max-w-4xl w-full p-8 sm:p-12 rounded-3xl shadow-2xl relative border-[12px] border-double border-amber-600/60 print:border-8 print:border-amber-700 print:shadow-none print:rounded-none"
        style={lang === "si" ? { fontFamily: "'Noto Serif Sinhala', 'Abhaya Libre', serif" } : {}}
      >
        
        {/* Inner Border */}
        <div className="border-2 border-amber-500/40 p-6 sm:p-10 rounded-2xl relative bg-amber-50/20">
          
          {/* Header Emblem & Title */}
          <div className="text-center space-y-3 mb-6">
            <div className="flex items-center justify-center mb-1">
              <img
                src="/logo.png"
                alt="Sagaramati Pirivena Logo"
                className="w-24 h-24 sm:w-28 sm:h-28 object-contain filter drop-shadow-md"
              />
            </div>

            <h1 className="text-3xl sm:text-4xl font-black text-brand-1 tracking-tight drop-shadow-sm font-serif">
              {lang === "en" ? certTitleEn : certTitleSi}
            </h1>
            <p className="text-xs sm:text-sm font-bold text-amber-900 uppercase tracking-wider">
              {lang === "en" ? certOrgEn : certOrgSi}
            </p>
          </div>

          {/* Body Content */}
          <div className="text-center space-y-5 text-ink/90 leading-relaxed font-medium">
            
            <p className="text-sm sm:text-base font-semibold text-gray-700">
              {lang === "en" ? certOfferedEn : certOfferedSi}
            </p>

            {/* Date */}
            <div>
              <div className="text-sm sm:text-base font-bold text-amber-900 bg-amber-100/70 py-2 px-6 rounded-full inline-block border border-amber-300 shadow-sm">
                {lang === "en" ? (
                  <>Scheduled for <span className="text-brand-1">{dana.month} {dana.day}, {dana.year || new Date().getFullYear()}</span></>
                ) : (
                  <>වෙන් කර ඇති දිනය: <span className="text-brand-1">{dana.month} මස {dana.day} වන දින ({dana.year || new Date().getFullYear()})</span></>
                )}
              </div>
            </div>

            {/* Meal Type Pill */}
            <div>
              <span className="inline-block text-xl sm:text-2xl font-black text-white bg-gradient-to-r from-brand-1 via-brand-2 to-amber-700 px-8 py-2.5 rounded-full shadow-md border-2 border-white">
                {lang === "en" ? mealNameEn : mealNameSi}
              </span>
            </div>

            {/* Donor Name */}
            <div className="py-2 space-y-1">
              <p className="text-xs text-gray-500 font-bold uppercase tracking-wider">
                {lang === "en" ? "Presented to / Offered by:" : "දායකත්වය පූජා කරනු ලබන්නේ:"}
              </p>
              <h2 className="text-2xl sm:text-3xl font-black text-brand-1 tracking-wide">
                {lang === "en" ? formatDonorDisplayEn() : formatDonorDisplaySi()}
              </h2>
              <p className="text-sm sm:text-base font-bold text-emerald-800 pt-1">
                {lang === "en" ? certAckEn : certAckSi}
              </p>
            </div>

            {/* Purpose / Arumuna */}
            {dana.purpose && (
              <div className="max-w-xl mx-auto bg-amber-100/50 p-4 rounded-2xl border border-amber-300/80 text-xs sm:text-sm">
                <span className="font-bold text-amber-900 block mb-1">
                  {lang === "en" ? "Special Purpose of Offering:" : "පුණ්‍යානුමෝදනා අරමුණ:"}
                </span>
                <p className="text-gray-800 font-semibold italic">"{dana.purpose}"</p>
              </div>
            )}

            {/* Blessing Stanza */}
            <div className="pt-4 border-t border-amber-200/80 space-y-3 max-w-2xl mx-auto">
              <p className="text-xs sm:text-sm font-semibold text-gray-800 leading-relaxed">
                {lang === "en" ? certBlessingEn : certBlessingSi}
              </p>

              <div className="bg-brand-1/5 py-3 px-6 rounded-2xl border border-brand-1/10">
                <p className="text-base sm:text-lg font-black text-brand-1">
                  {lang === "en" ? certStanzaEn : certStanzaSi}
                </p>
              </div>
            </div>

          </div>

          {/* Footer & Signature Block */}
          <div className="mt-12 pt-6 border-t border-amber-300/80 flex flex-col sm:flex-row items-center justify-between gap-6 text-xs text-gray-600">
            <div className="text-center sm:text-left space-y-1">
              <p className="font-bold text-ink">
                {lang === "en" ? "Issued Date: " : "නිකුත් කළ දිනය: "}{new Date().toLocaleDateString('en-GB')}
              </p>
              <p className="font-semibold text-gray-500">
                {lang === "en" ? "Registration ID: #" : "ලියාපදිංචි අංකය: #"}{dana.id}
              </p>
              <p className="text-[10px] text-amber-800 font-bold">
                {lang === "en" ? "Sagaramati Official Merit Certificate" : "සාගරමති පිරිවෙන් නිල පුණ්‍ය පත්‍රය"}
              </p>
            </div>

            <div className="text-center space-y-2">
              <div className="w-48 border-b-2 border-dashed border-gray-400 mx-auto" />
              <p className="font-bold text-ink text-sm">
                {lang === "en" ? "Sagaramati Pirivena" : "සාගරමති පිරිවෙන"}
              </p>
              <p className="text-[11px] font-semibold text-gray-500">
                {lang === "en" ? certSigEn : certSigSi}
              </p>
            </div>
          </div>

        </div>
      </div>
    </div>
  );
};

export default CertificateScreen;
