import { Request, Response } from "express";
import prisma from "../config/db.js";
import { fetchAuditLogs } from "../services/audit.service.js";

const DEFAULT_VISION = "ශ්‍රී සම්බුද්ධ ශාසනයේ චිරස්ථිතිය උදෙසා උසස් සද්ධර්ම අධ්‍යාපනයෙන්, ශාසනික ගුණධර්මයන්ගෙන් හා නූතන තාක්ෂණික කුසලතාවයන්ගෙන් පරිපූර්ණ බුද්ධිමත් ශිෂ්‍ය පරපුරක් හා ශ්‍රද්ධාබුද්ධියෙන් පිරි සමාජයක් බිහිකිරීම.";
const DEFAULT_MISSION = "සාගරමති පිරිවෙණ මගින් පූජනීය සංඝරත්නයට හා සාමණේර හිමිවරුන්ට පරිපූර්ණ ත්‍රිපිටක ධර්ම අධ්‍යාපනය හා ශාසනික වගකීම් සපයමින්, දායක දායිකාවන්ට ශ්‍රද්ධා වර්ධනය කරවන දානමය පින්කම් හා ඩිජිටල් තාක්ෂණික සේවාවන් විනිවිදභාවයෙන් යුතුව ඉටුකිරීම.";

// Public: Get all settings
export const getSettings = async (req: Request, res: Response): Promise<void> => {
  try {
    const settings = await prisma.siteSetting.findMany();
    const map: Record<string, string> = {
      vision: DEFAULT_VISION,
      mission: DEFAULT_MISSION,
      cert_title_en: "Official Certificate of Dana Offering",
      cert_title_si: "පුණ්‍යානුමෝදනා ශ්‍රී සන්නස් පත්‍රය",
      cert_org_en: "Sagaramati Buddhist Monastery & Pirivena",
      cert_org_si: "සාගරමති පිරිවෙන් සංවර්ධන සභාව",
      cert_offered_en: "Offered to the Most Venerable Maha Sangha of Sagaramati Monastery,",
      cert_offered_si: "කන්දෙගම ඓතිහාසික ධනංජය රජමහා විහාරස්ථ සාගරමති පිරිවෙනේ නේවාසික මහා සංඝරත්නය උදෙසා,",
      cert_ack_en: "This certificate gratefully acknowledges the devout sponsorship of this sacred merit.",
      cert_ack_si: "මෙම ශ්‍රේෂ්ඨ මහඟු දානමය පුණ්‍යකර්මය සාදරයෙන් අනුමත කොට පින් අනුමෝදන් කරමු.",
      cert_blessing_en: "May all immense virtues generated by this noble deed of Dana be shared with you, your family, loved ones, and departed ancestors for their peaceful well-being.",
      cert_blessing_si: "මෙම උතුම් දානමය පින්කමෙන් රැස්කරගන්නා ලද සියලු මහා කුසල් සම්පත් ඔබතුමා ඇතුළු පවුලේ සැමටත්, ඤාති මිත්‍රාදීන්ටත්, පරලොවප්‍රාප්ත ඤාතීන්ටත් අනුමෝදන් වේවා!",
      cert_stanza_en: "May the blessings of the Noble Triple Gem grant you good health, prosperity, happiness, and ultimate peace of Nibbana!",
      cert_stanza_si: "තුනුරුවනේ අනන්ත ගුණ බලයෙන් ඔබ සැමට දීර්ඝායුෂ, නීරෝගීභාවය, සාමය, සතුට හා උතුම් චතුරාර්ය සත්‍ය අවබෝධ වේවා!",
      cert_footer_sig_en: "With the blessings of the Venerable Sangha",
      cert_footer_sig_si: "ගෞරවනීය මහා සංඝරත්නයේ ආශීර්වාදයෙන්",

      // English Letter
      letter_org_title: "Sagaramati Pirivena Development Council",
      letter_patron_1: "Patron: Ven. Gonawala Sudassilankara Nahimipano",
      letter_patron_2: "Chief President: Ven. Kandegama Deepawansalankara Thero",
      letter_patron_3: "Chief Secretary: Ven. Horana Vijayawansalankara Thero",
      letter_patron_4: "Treasurer: Mr. H. M. Gunapala",
      letter_president: "Chief Organizer: Mr. K. G. C. Gunawardena",
      letter_address_1: "Sagaramati Pirivena",
      letter_address_2: "Dhananjaya Rajamaha Viharaya",
      letter_address_3: "Kandegama, Polonnaruwa",
      letter_phone: "027-3272215",
      letter_whatsapp: "076-3272215",
      letter_email: "psagaramathi@yahoo.com",
      letter_subject: "Annual Dana Offering Sponsorship",
      letter_body_p1: "We express our heartfelt gratitude to {recipient} for coming forward to sponsor the requisite needs of the resident monks of Sagaramati Pirivena, Dhananjaya Rajamaha Viharaya, Kandegama.",
      letter_body_p2: "Accordingly, we kindly remind you that every year on {month} {day}, the sponsorship for \"{purpose}\" has been reserved in your name.",
      letter_body_p3: "Therefore, we respectfully remind you that for this year {year}, on {month} {day}, monks will be present for your {meal_type}. You may attend in person to offer the Dana or contribute by depositing funds into the temple bank account below. The estimated expense for morning and midday meals is approximately LKR 5000.",
      letter_bank_name: "People's Bank - Aralaganwila Branch",
      letter_bank_acc: "253200150044402",
      letter_bank_owner: "Sagaramati Pirivena Development Council",
      letter_sig_pres: "President",
      letter_sig_sec: "Secretary",

      // Sinhala Letter
      letter_org_title_si: "සාගරමති පිරිවෙන් සංවර්ධන සභාව",
      letter_patron_1_si: "අනුශාසක : පූජ්‍ය ගෝණවල සුදස්සීලංකාර නාහිමිපාණෝ",
      letter_patron_2_si: "ප්‍රධාන සභාපති : පූජ්‍ය කන්දේගම දීපවංසාලංකාර හිමි",
      letter_patron_3_si: "ප්‍රධාන ලේකම් : පූජ්‍ය හොරණ විජයවංසාලංකාර හිමි",
      letter_patron_4_si: "භාණ්ඩාගාරික : එච්. එම්. ගුණපාල මහතා",
      letter_president_si: "ප්‍රධාන සංවිධායක : කේ. ජී. සී. ගුණවර්ධන මහතා",
      letter_address_1_si: "සාගරමති පිරිවෙන",
      letter_address_2_si: "ධනංජය රජමහා විහාරය",
      letter_address_3_si: "කන්දෙගම, පොළොන්නරුව",
      letter_subject_si: "වාර්ෂික දානමය පුණ්‍යකර්මය පිළිබඳ පූර්ව දැනුම්දීම",
      letter_body_p1_si: "කන්දෙගම ඓතිහාසික ධනංජය රජමහා විහාරස්ථ සාගරමති පිරිවෙනේ නේවාසික මහා සංඝරත්නයේ සිව්පසය උදෙසා {recipient} විසින් ඉදිරිපත්ව දායකත්වය ලබාදීම පිළිබඳව අපගේ ගෞරවනීය ස්තූතිය පුද කරමු.",
      letter_body_p2_si: "ඒ අනුව, සෑම වසරකම {month} මස {day} වන දින \"{purpose}\" සඳහා වන දානමය දායකත්වය ඔබතුමන්ලාගේ නමින් වෙන් කර ඇති බව කාරුණිකව මතක් කර සිටිමු.",
      letter_body_p3_si: "එබැවින්, මෙවර {year} වසරේ {month} මස {day} වන දිනට යෙදෙන ඔබගේ {meal_type} සඳහා මහා සංඝරත්නය වඩමවන බව ගෞරවයෙන් දැනුම් දෙමු. ඔබට පැමිණ දානය පූජා කිරීමට හෝ පහත සඳහන් විහාරස්ථ බැංකු ගිණුමට ආධාර තැන්පත් කිරීමට හැක. හීල් සහ දවල් දානමය වියදම ආසන්න වශයෙන් රුපියල් 5000 ක් පමණ වේ.",
      letter_bank_name_si: "මහජන බැංකුව - අරලගංවිල ශාඛාව",
      letter_bank_acc_si: "253200150044402",
      letter_bank_owner_si: "සාගරමති පිරිවෙන් සංවර්ධන සභාව",
      letter_sig_pres_si: "සභාපති",
      letter_sig_sec_si: "ලේකම්",
    };

    settings.forEach((s) => {
      map[s.key] = s.value;
    });

    res.status(200).json(map);
  } catch (error) {
    console.error("Error fetching settings:", error);
    res.status(500).json({ message: "Internal server error" });
  }
};

// Protected: Update setting (Admin / Super Admin)
export const updateSetting = async (req: any, res: Response): Promise<void> => {
  try {
    const role = req.user?.role;
    if (role !== "SUPER_ADMIN" && role !== "ADMIN") {
      res.status(403).json({ message: "Only Admin or Super Admin can edit settings." });
      return;
    }

    const { key, value, settings } = req.body;

    if (settings && typeof settings === "object") {
      const updates = [];
      for (const [k, v] of Object.entries(settings)) {
        updates.push(
          prisma.siteSetting.upsert({
            where: { key: k },
            update: { value: String(v) },
            create: { key: k, value: String(v) },
          })
        );
      }
      await Promise.all(updates);
      res.status(200).json({ message: "Settings updated successfully" });
      return;
    }

    if (!key || value === undefined) {
      res.status(400).json({ message: "Key and value are required." });
      return;
    }

    const updated = await prisma.siteSetting.upsert({
      where: { key },
      update: { value: String(value) },
      create: { key, value: String(value) },
    });

    res.status(200).json({ message: "Setting updated successfully", data: updated });
  } catch (error) {
    console.error("Error updating setting:", error);
    res.status(500).json({ message: "Internal server error" });
  }
};

// Protected: Get Audit Logs (Admin / Super Admin)
export const getAuditLogs = async (req: Request, res: Response): Promise<void> => {
  try {
    const logs = await fetchAuditLogs(150);
    res.status(200).json({ success: true, data: logs });
  } catch (error) {
    console.error("Error fetching audit logs:", error);
    res.status(500).json({ message: "Internal server error" });
  }
};

