import React, { useEffect, useState } from "react";
import { useAuth } from "../../context/AuthContext";
import { API_BASE_URL } from "../../libs/api";

const renderHighlightedText = (template: string, values: Record<string, string>) => {
  let tokenized = template;
  Object.keys(values).forEach((key) => {
    const regex = new RegExp(`\\{${key}\\}`, "g");
    tokenized = tokenized.replace(regex, `__HL_${key}__`);
  });

  const parts = tokenized.split(/(__HL_[a-zA-Z0-9_]+__)/g);

  return parts.map((part, index) => {
    if (part.startsWith("__HL_") && part.endsWith("__")) {
      const key = part.slice(5, -2);
      const val = values[key];
      if (val !== undefined) {
        return (
          <strong key={index} className="text-brand-1 font-bold">
            {val}
          </strong>
        );
      }
    }
    return part;
  });
};

export const AdminTemplateEditorScreen: React.FC = () => {
  const { token } = useAuth();
  const [activeTab, setActiveTab] = useState<"cert" | "letter">("cert");
  const [letterFormLang, setLetterFormLang] = useState<"si" | "en">("si");
  const [loading, setLoading] = useState<boolean>(true);
  const [saving, setSaving] = useState<boolean>(false);
  const [successMsg, setSuccessMsg] = useState<string>("");

  const [settings, setSettings] = useState<Record<string, string>>({
    // Certificate
    cert_title_en: "Official Certificate of Dana Offering",
    cert_title_si: "දානමය පූජෝපහාර සාධු සම්මාන සහතිකය",
    cert_org_en: "Sāgaramati Buddhist Monastery & Pirivena",
    cert_org_si: "සාගරමති බෞද්ධ සංඝ මධ්‍යස්ථානය සහ පිරිවෙන",
    cert_offered_en: "Offered to the Most Venerable Maha Sangha of Sāgaramati Monastery,",
    cert_offered_si: "අතිපූජනීය සාගරමති මහා විහාරවාසී ගරුතර මහා සංඝරත්නය උදෙසා,",
    cert_ack_en: "This certificate gratefully acknowledges the devout sponsorship of this sacred merit.",
    cert_ack_si: "මෙම පූජනීය දානමය පූජෝපහාරය වෙනුවෙන් සිදුකරනු ලබන වාර්ෂික දායකත්වය අභිනන්දනයෙන් යුතුව සටහන් කරමු.",
    cert_blessing_en: "May all immense virtues generated by this noble deed of Dana be shared with you, your family, loved ones, and departed ancestors for their peaceful well-being.",
    cert_blessing_si: "මෙම උතුම් දානමය පුණ්‍යකර්මයෙන් ජනිත සියලු අනන්ත පුණ්‍ය සම්පත් ඔබ වෙතත්, පවුලේ සැමටත්, මියගිය ඥාතීන්ටත් අනුමෝදන් වේවා!",
    cert_stanza_en: "May the blessings of the Noble Triple Gem grant you good health, prosperity, happiness, and ultimate peace of Nibbana!",
    cert_stanza_si: "උතුම් තෙරුවණ් සරණින් ඔබට නීරෝගී සුවය, දීර්ඝායුෂ සහ උතුම් චතුරාර්ය සත්‍ය අවබෝධ වේවා!",
    cert_footer_sig_en: "With the blessings of the Venerable Sangha",
    cert_footer_sig_si: "ගරුතර මහා සංඝරත්නයේ ආශීර්වාදයෙන්",

    // Letter English
    letter_org_title: "Sāgaramati Pirivena Development Council",
    letter_patron_1: "Patron: Ven. Gonawala Sudassilankara Nahimipano",
    letter_patron_2: "Chief President: Ven. Kandegama Deepawansalankara Thero",
    letter_patron_3: "Chief Secretary: Ven. Horana Vijayawansalankara Thero",
    letter_patron_4: "Treasurer: Mr. H. M. Gunapala",
    letter_president: "Chief Organizer: Mr. K. G. C. Gunawardena",
    letter_address_1: "Sāgaramati Pirivena",
    letter_address_2: "Dhananjaya Rajamaha Viharaya",
    letter_address_3: "Kandegama, Polonnaruwa",
    letter_phone: "027-3272215",
    letter_whatsapp: "076-3272215",
    letter_email: "psagaramathi@yahoo.com",
    letter_subject: "Annual Dana Offering Sponsorship",
    letter_body_p1: "We express our heartfelt gratitude to {recipient} for coming forward to sponsor the requisite needs of the resident monks of Sāgaramati Pirivena, Dhananjaya Rajamaha Viharaya, Kandegama.",
    letter_body_p2: "Accordingly, we kindly remind you that every year on {month} {day}, the sponsorship for \"{purpose}\" has been reserved in your name.",
    letter_body_p3: "Therefore, we respectfully remind you that for this year {year}, on {month} {day}, monks will be present for your {meal_type}. You may attend in person to offer the Dana or contribute by depositing funds into the temple bank account below.",
    letter_bank_name: "People's Bank - Aralaganwila Branch",
    letter_bank_acc: "253200150044402",
    letter_bank_owner: "Sāgaramati Pirivena Development Council",
    letter_sig_pres: "President",
    letter_sig_sec: "Secretary",

    // Letter Sinhala
    letter_org_title_si: "සාගරමති පිරිවෙන් සංවර්ධන සභාව",
    letter_patron_1_si: "අනුශාසක: පූජ්‍ය ගෝනවල සුදස්සිලංකාර නාහිමිපාණන්",
    letter_patron_2_si: "ගරු සභාපති: පූජ්‍ය කන්දේගම දීපවංසාලංකාර හිමි",
    letter_patron_3_si: "ගරු ලේකම්: පූජ්‍ය හොරණ විජයවංසාලංකාර හිමි",
    letter_patron_4_si: "භාණ්ඩාගාරික: එච්. එම්. ගුණපාල මහතා",
    letter_president_si: "ප්‍රධාන සංවිධායක: කේ. ජී. සී. ගුණවර්ධන මහතා",
  });

  useEffect(() => {
    fetchSettings();
  }, []);

  const fetchSettings = async () => {
    try {
      setLoading(true);
      const res = await fetch(`${API_BASE_URL}/settings`);
      if (res.ok) {
        const data = await res.json();
        setSettings((prev) => ({ ...prev, ...data }));
      }
    } catch (e) {
      console.error("Error loading settings:", e);
    } finally {
      setLoading(false);
    }
  };

  const handleChange = (key: string, val: string) => {
    setSettings((prev) => ({ ...prev, [key]: val }));
  };

  const handleSaveAll = async (e: React.FormEvent) => {
    e.preventDefault();
    setSaving(true);
    setSuccessMsg("");

    try {
      const res = await fetch(`${API_BASE_URL}/settings`, {
        method: "PUT",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({ settings }),
      });

      if (res.ok) {
        setSuccessMsg("Template settings saved successfully!");
        setTimeout(() => setSuccessMsg(""), 4000);
      } else {
        alert("Failed to save settings.");
      }
    } catch (e) {
      console.error("Error saving template settings:", e);
      alert("Error saving settings.");
    } finally {
      setSaving(false);
    }
  };

  if (loading) {
    return <div className="p-12 text-center text-sm font-semibold text-subtle">Loading template editor...</div>;
  }

  return (
    <div className="max-w-7xl mx-auto space-y-6 pb-12">
      {/* Header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 bg-white p-6 rounded-2xl shadow-sm border border-brand-1/10">
        <div>
          <h1 className="text-2xl font-black text-ink flex items-center gap-2">
            Template Editor (සහතික සහ ලිපි සැකිලි සංස්කාරකය)
          </h1>
          <p className="text-xs text-subtle mt-1">
            Customize official Dana Merit Certificate and Monthly Reminder Letter template texts.
          </p>
        </div>

        <button
          onClick={handleSaveAll}
          disabled={saving}
          className="px-6 py-3 bg-emerald-700 hover:bg-emerald-800 text-white font-bold text-xs sm:text-sm rounded-xl shadow-md transition-all shrink-0 active:scale-95 disabled:opacity-50"
        >
          {saving ? "Saving Templates..." : "Save All Templates"}
        </button>
      </div>

      {successMsg && (
        <div className="p-4 bg-emerald-50 border border-emerald-200 text-emerald-800 text-sm font-bold rounded-xl animate-fade-in">
          {successMsg}
        </div>
      )}

      {/* Tabs Header */}
      <div className="border-b border-gray-200 flex gap-6 text-sm font-bold text-gray-500 pt-2 overflow-x-auto">
        <button
          onClick={() => setActiveTab("cert")}
          className={`pb-3 flex items-center gap-2 transition-all border-b-2 whitespace-nowrap ${
            activeTab === "cert"
              ? "border-emerald-700 text-emerald-800 font-extrabold"
              : "border-transparent hover:text-ink"
          }`}
        >
          1. Dana Merit Certificate Template
        </button>

        <button
          onClick={() => setActiveTab("letter")}
          className={`pb-3 flex items-center gap-2 transition-all border-b-2 whitespace-nowrap ${
            activeTab === "letter"
              ? "border-emerald-700 text-emerald-800 font-extrabold"
              : "border-transparent hover:text-ink"
          }`}
        >
          2. Monthly Reminder Letter Template
        </button>
      </div>

      {/* Certificate Editor */}
      {activeTab === "cert" && (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          <div className="bg-white p-6 rounded-2xl border border-gray-200 space-y-4 shadow-sm">
            <h3 className="font-extrabold text-base text-ink border-b pb-2">Certificate Texts (English &amp; Sinhala)</h3>

            <div>
              <label className="block text-xs font-bold text-gray-700 mb-1">Certificate Title (Sinhala)</label>
              <input
                type="text"
                value={settings.cert_title_si || ""}
                onChange={(e) => handleChange("cert_title_si", e.target.value)}
                className="w-full p-2.5 border rounded-xl text-xs font-medium focus:border-brand-1 outline-none"
              />
            </div>

            <div>
              <label className="block text-xs font-bold text-gray-700 mb-1">Certificate Title (English)</label>
              <input
                type="text"
                value={settings.cert_title_en || ""}
                onChange={(e) => handleChange("cert_title_en", e.target.value)}
                className="w-full p-2.5 border rounded-xl text-xs font-medium focus:border-brand-1 outline-none"
              />
            </div>

            <div>
              <label className="block text-xs font-bold text-gray-700 mb-1">Organization Name (Sinhala)</label>
              <input
                type="text"
                value={settings.cert_org_si || ""}
                onChange={(e) => handleChange("cert_org_si", e.target.value)}
                className="w-full p-2.5 border rounded-xl text-xs font-medium focus:border-brand-1 outline-none"
              />
            </div>

            <div>
              <label className="block text-xs font-bold text-gray-700 mb-1">Organization Name (English)</label>
              <input
                type="text"
                value={settings.cert_org_en || ""}
                onChange={(e) => handleChange("cert_org_en", e.target.value)}
                className="w-full p-2.5 border rounded-xl text-xs font-medium focus:border-brand-1 outline-none"
              />
            </div>

            <div>
              <label className="block text-xs font-bold text-gray-700 mb-1">Acknowledgment Text (Sinhala)</label>
              <textarea
                rows={3}
                value={settings.cert_ack_si || ""}
                onChange={(e) => handleChange("cert_ack_si", e.target.value)}
                className="w-full p-2.5 border rounded-xl text-xs font-medium focus:border-brand-1 outline-none"
              />
            </div>

            <div>
              <label className="block text-xs font-bold text-gray-700 mb-1">Blessing Text (Sinhala)</label>
              <textarea
                rows={3}
                value={settings.cert_stanza_si || ""}
                onChange={(e) => handleChange("cert_stanza_si", e.target.value)}
                className="w-full p-2.5 border rounded-xl text-xs font-medium focus:border-brand-1 outline-none"
              />
            </div>
          </div>

          <div className="bg-amber-50/50 p-6 rounded-2xl border border-amber-200 shadow-sm space-y-4">
            <h3 className="font-extrabold text-base text-amber-900 border-b border-amber-200 pb-2">Live Certificate Preview</h3>
            <div className="bg-white p-6 rounded-xl border-4 border-amber-500/30 text-center space-y-3 shadow-md">
              <h4 className="text-lg font-black text-amber-900">{settings.cert_title_si}</h4>
              <p className="text-xs font-bold text-gray-600">{settings.cert_org_si}</p>
              <div className="w-16 h-0.5 bg-amber-500 mx-auto rounded-full" />
              <p className="text-xs text-gray-700 font-medium leading-relaxed px-4">{settings.cert_ack_si}</p>
              <p className="text-xs text-amber-800 font-bold italic pt-2">{settings.cert_stanza_si}</p>
            </div>
          </div>
        </div>
      )}

      {/* Letter Editor */}
      {activeTab === "letter" && (
        <div className="bg-white p-6 rounded-2xl border border-gray-200 shadow-sm space-y-6">
          <div className="flex justify-between items-center border-b pb-4">
            <h3 className="font-extrabold text-base text-ink">Monthly Reminder Letter Settings</h3>
            <div className="flex gap-2 bg-gray-100 p-1 rounded-xl">
              <button
                onClick={() => setLetterFormLang("si")}
                className={`px-3 py-1 text-xs font-bold rounded-lg transition-all ${
                  letterFormLang === "si" ? "bg-white text-emerald-800 shadow-sm" : "text-gray-600"
                }`}
              >
                Sinhala Version
              </button>
              <button
                onClick={() => setLetterFormLang("en")}
                className={`px-3 py-1 text-xs font-bold rounded-lg transition-all ${
                  letterFormLang === "en" ? "bg-white text-emerald-800 shadow-sm" : "text-gray-600"
                }`}
              >
                English Version
              </button>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs font-bold">
            <div>
              <label className="block text-gray-700 mb-1">Organization Title</label>
              <input
                type="text"
                value={letterFormLang === "si" ? settings.letter_org_title_si || "" : settings.letter_org_title || ""}
                onChange={(e) =>
                  handleChange(letterFormLang === "si" ? "letter_org_title_si" : "letter_org_title", e.target.value)
                }
                className="w-full p-2.5 border rounded-xl font-medium outline-none focus:border-brand-1"
              />
            </div>
            <div>
              <label className="block text-gray-700 mb-1">Letter Subject</label>
              <input
                type="text"
                value={settings.letter_subject || ""}
                onChange={(e) => handleChange("letter_subject", e.target.value)}
                className="w-full p-2.5 border rounded-xl font-medium outline-none focus:border-brand-1"
              />
            </div>
          </div>

          <div>
            <label className="block text-xs font-bold text-gray-700 mb-1">
              Body Paragraph 1 (Use placeholders: {"{recipient}"}, {"{month}"}, {"{day}"}, {"{meal_type}"})
            </label>
            <textarea
              rows={3}
              value={settings.letter_body_p1 || ""}
              onChange={(e) => handleChange("letter_body_p1", e.target.value)}
              className="w-full p-2.5 border rounded-xl text-xs font-medium focus:border-brand-1 outline-none leading-relaxed"
            />
            <div className="mt-1 text-[11px] text-brand-1 font-semibold">
              Preview: {renderHighlightedText(settings.letter_body_p1 || "", { recipient: "Sunil Perera" })}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
