import React, { useEffect, useState } from "react";
import { useAuth } from "../../context/AuthContext";
import { API_BASE_URL } from "../../libs/api";

const renderHighlightedText = (template: string, values: Record<string, string>) => {
  let tokenized = template;
  Object.keys(values).forEach((key) => {
    const regex = new RegExp(`\\{${key}\\}`, "g");
    tokenized = tokenized.replace(regex, `__HL_${key}__`);
  });

  const parts = tokenized.split(/(__HL_[a-zA-Z0-9_]+__)/g);

  return parts.map((part, index) => {
    if (part.startsWith("__HL_") && part.endsWith("__")) {
      const key = part.slice(5, -2);
      const val = values[key];
      if (val !== undefined) {
        return (
          <strong key={index} className="text-brand-1 font-bold">
            {val}
          </strong>
        );
      }
    }
    return part;
  });
};

export const AdminTemplateEditorScreen: React.FC = () => {
  const { token } = useAuth();
  const [activeTab, setActiveTab] = useState<"cert" | "letter">("cert");
  const [letterFormLang, setLetterFormLang] = useState<"si" | "en">("si");
  const [loading, setLoading] = useState<boolean>(true);
  const [saving, setSaving] = useState<boolean>(false);
  const [successMsg, setSuccessMsg] = useState<string>("");

  const [settings, setSettings] = useState<Record<string, string>>({
    // Certificate
    cert_title_en: "Official Certificate of Dana Offering",
    cert_title_si: "පුණ්‍යානුමෝදනා ශ්‍රී සන්නස් පත්‍රය",
    cert_org_en: "Sagaramati Buddhist Monastery & Pirivena",
    cert_org_si: "සාගරමති පිරිවෙන් සංවර්ධන සභාව",
    cert_offered_en: "Offered to the Most Venerable Maha Sangha of Sagaramati Monastery,",
    cert_offered_si: "කන්දෙගම ඓතිහාසික ධනංජය රජමහා විහාරස්ථ සාගරමති පිරිවෙනේ නේවාසික මහා සංඝරත්නය උදෙසා,",
    cert_ack_en: "This certificate gratefully acknowledges the devout sponsorship of this sacred merit.",
    cert_ack_si: "මෙම ශ්‍රේෂ්ඨ මහඟු දානමය පුණ්‍යකර්මය සාදරයෙන් අනුමත කොට පින් අනුමෝදන් කරමු.",
    cert_blessing_en: "May all immense virtues generated by this noble deed of Dana be shared with you, your family, loved ones, and departed ancestors for their peaceful well-being.",
    cert_blessing_si: "මෙම උතුම් දානමය පින්කමෙන් රැස්කරගන්නා ලද සියලු මහා කුසල් සම්පත් ඔබතුමා ඇතුළු පවුලේ සැමටත්, ඤාති මිත්‍රාදීන්ටත්, පරලොවප්‍රාප්ත ඤාතීන්ටත් අනුමෝදන් වේවා!",
    cert_stanza_en: "May the blessings of the Noble Triple Gem grant you good health, prosperity, happiness, and ultimate peace of Nibbana!",
    cert_stanza_si: "තුනුරුවනේ අනන්ත ගුණ බලයෙන් ඔබ සැමට දීර්ඝායුෂ, නීරෝගීභාවය, සාමය, සතුට හා උතුම් චතුරාර්ය සත්‍ය අවබෝධ වේවා!",
    cert_footer_sig_en: "With the blessings of the Venerable Sangha",
    cert_footer_sig_si: "ගෞරවනීය මහා සංඝරත්නයේ ආශීර්වාදයෙන්",

    // Letter English
    letter_org_title: "Sagaramati Pirivena Development Council",
    letter_patron_1: "Patron: Ven. Gonawala Sudassilankara Nahimipano",
    letter_patron_2: "Chief President: Ven. Kandegama Deepawansalankara Thero",
    letter_patron_3: "Chief Secretary: Ven. Horana Vijayawansalankara Thero",
    letter_patron_4: "Treasurer: Mr. H. M. Gunapala",
    letter_president: "Chief Organizer: Mr. K. G. C. Gunawardena",
    letter_address_1: "Sagaramati Pirivena",
    letter_address_2: "Dhananjaya Rajamaha Viharaya",
    letter_address_3: "Kandegama, Polonnaruwa",
    letter_phone: "027-3272215",
    letter_whatsapp: "076-3272215",
    letter_email: "psagaramathi@yahoo.com",
    letter_subject: "Annual Dana Offering Sponsorship",
    letter_body_p1: "We express our heartfelt gratitude to {recipient} for coming forward to sponsor the requisite needs of the resident monks of Sagaramati Pirivena, Dhananjaya Rajamaha Viharaya, Kandegama.",
    letter_body_p2: "Accordingly, we kindly remind you that every year on {month} {day}, the sponsorship for \"{purpose}\" has been reserved in your name.",
    letter_body_p3: "Therefore, we respectfully remind you that for this year {year}, on {month} {day}, monks will be present for your {meal_type}. You may attend in person to offer the Dana or contribute by depositing funds into the temple bank account below. The estimated expense for morning and midday meals is approximately LKR 5000.",
    letter_bank_name: "People's Bank - Aralaganwila Branch",
    letter_bank_acc: "253200150044402",
    letter_bank_owner: "Sagaramati Pirivena Development Council",
    letter_sig_pres: "President",
    letter_sig_sec: "Secretary",

    // Letter Sinhala
    letter_org_title_si: "සාගරමති පිරිවෙන් සංවර්ධන සභාව",
    letter_patron_1_si: "අනුශාසක : පූජ්‍ය ගෝණවල සුදස්සීලංකාර නාහිමිපාණෝ",
    letter_patron_2_si: "ප්‍රධාන සභාපති : පූජ්‍ය කන්දේගම දීපවංසාලංකාර හිමි",
    letter_patron_3_si: "ප්‍රධාන ලේකම් : පූජ්‍ය හොරණ විජයවංසාලංකාර හිමි",
    letter_patron_4_si: "භාණ්ඩාගාරික : එච්. එම්. ගුණපාල මහතා",
    letter_president_si: "ප්‍රධාන සංවිධායක : කේ. ජී. සී. ගුණවර්ධන මහතා",
  });

  useEffect(() => {
    fetchSettings();
  }, []);

  const fetchSettings = async () => {
    try {
      setLoading(true);
      const res = await fetch(`${API_BASE_URL}/settings`);
      if (res.ok) {
        const data = await res.json();
        setSettings((prev) => ({ ...prev, ...data }));
      }
    } catch (e) {
      console.error("Error loading settings:", e);
    } finally {
      setLoading(false);
    }
  };

  const handleChange = (key: string, val: string) => {
    setSettings((prev) => ({ ...prev, [key]: val }));
  };

  const handleSaveAll = async (e: React.FormEvent) => {
    e.preventDefault();
    setSaving(true);
    setSuccessMsg("");

    try {
      const res = await fetch(`${API_BASE_URL}/settings`, {
        method: "PUT",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({ settings }),
      });

      if (res.ok) {
        setSuccessMsg("Template settings saved successfully!");
        setTimeout(() => setSuccessMsg(""), 4000);
      } else {
        alert("Failed to save settings.");
      }
    } catch (e) {
      console.error("Error saving template settings:", e);
      alert("Error saving settings.");
    } finally {
      setSaving(false);
    }
  };

  if (loading) {
    return <div className="p-12 text-center text-sm font-semibold text-subtle">Loading template editor...</div>;
  }

  return (
    <div className="max-w-7xl mx-auto space-y-6 pb-12">
      {/* Header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 bg-white p-6 rounded-2xl shadow-sm border border-brand-1/10">
        <div>
          <h1 className="text-2xl font-black text-ink flex items-center gap-2">
            Template Editor (සහතික & ලිපි ටෙම්ප්ලේට්)
          </h1>
          <p className="text-xs text-subtle mt-1">
            Customize official Dana Merit Certificate and Monthly Reminder Letter template texts.
          </p>
        </div>

        <button
          onClick={handleSaveAll}
          disabled={saving}
          className="px-6 py-3 bg-emerald-700 hover:bg-emerald-800 text-white font-bold text-xs sm:text-sm rounded-xl shadow-md transition-all shrink-0 active:scale-95 disabled:opacity-50"
        >
          {saving ? "Saving Templates..." : "Save All Templates"}
        </button>
      </div>

      {successMsg && (
        <div className="p-4 bg-emerald-50 border border-emerald-200 text-emerald-800 text-sm font-bold rounded-xl animate-fade-in">
          {successMsg}
        </div>
      )}

      {/* Tabs Header */}
      <div className="border-b border-gray-200 flex gap-6 text-sm font-bold text-gray-500 pt-2">
        <button
          onClick={() => setActiveTab("cert")}
          className={`pb-3 flex items-center gap-2 transition-all border-b-2 ${
            activeTab === "cert"
              ? "border-emerald-700 text-emerald-800 font-extrabold"
              : "border-transparent hover:text-ink"
          }`}
        >
          1. Dana Merit Certificate Template (සහතික පත්‍ර ටෙම්ප්ලේට් එක)
        </button>

        <button
          onClick={() => setActiveTab("letter")}
          className={`pb-3 flex items-center gap-2 transition-all border-b-2 ${
            activeTab === "letter"
              ? "border-emerald-700 text-emerald-800 font-extrabold"
              : "border-transparent hover:text-ink"
          }`}
        >
          2. Monthly Reminder Letter Template (දැනුම්දීමේ ලිපි ටෙම්ප්ලේට් එක)
        </button>
      </div>

      <form onSubmit={handleSaveAll} className="space-y-6">
        {/* TAB 1: CERTIFICATE TEMPLATE */}
        {activeTab === "cert" && (
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {/* Form Column */}
            <div className="bg-white p-6 rounded-2xl border border-brand-1/10 shadow-sm space-y-4">
              <h2 className="text-lg font-bold text-ink border-b pb-2">English Certificate Texts</h2>

              <div>
                <label className="block text-xs font-bold text-ink mb-1">Header Title (English)</label>
                <input
                  type="text"
                  value={settings.cert_title_en || ""}
                  onChange={(e) => handleChange("cert_title_en", e.target.value)}
                  className="w-full px-3.5 py-2 rounded-xl text-xs border border-gray-300 focus:border-brand-1 outline-none"
                />
              </div>

              <div>
                <label className="block text-xs font-bold text-ink mb-1">Organization Sub-title (English)</label>
                <input
                  type="text"
                  value={settings.cert_org_en || ""}
                  onChange={(e) => handleChange("cert_org_en", e.target.value)}
                  className="w-full px-3.5 py-2 rounded-xl text-xs border border-gray-300 focus:border-brand-1 outline-none"
                />
              </div>

              <div>
                <label className="block text-xs font-bold text-ink mb-1">Offered To Phrase (English)</label>
                <input
                  type="text"
                  value={settings.cert_offered_en || ""}
                  onChange={(e) => handleChange("cert_offered_en", e.target.value)}
                  className="w-full px-3.5 py-2 rounded-xl text-xs border border-gray-300 focus:border-brand-1 outline-none"
                />
              </div>

              <div>
                <label className="block text-xs font-bold text-ink mb-1">Acknowledgment Text (English)</label>

                <textarea
                  rows={2}
                  value={settings.cert_ack_en || ""}
                  onChange={(e) => handleChange("cert_ack_en", e.target.value)}
                  className="w-full px-3.5 py-2 rounded-xl text-xs border border-gray-300 focus:border-brand-1 outline-none"
                />
              </div>

              <div>
                <label className="block text-xs font-bold text-ink mb-1">Blessings Stanza Paragraph (English)</label>
                <textarea
                  rows={3}
                  value={settings.cert_blessing_en || ""}
                  onChange={(e) => handleChange("cert_blessing_en", e.target.value)}
                  className="w-full px-3.5 py-2 rounded-xl text-xs border border-gray-300 focus:border-brand-1 outline-none"
                />
              </div>

              <div>
                <label className="block text-xs font-bold text-ink mb-1">Highlight Blessing Box (English)</label>
                <textarea
                  rows={2}
                  value={settings.cert_stanza_en || ""}
                  onChange={(e) => handleChange("cert_stanza_en", e.target.value)}
                  className="w-full px-3.5 py-2 rounded-xl text-xs border border-gray-300 focus:border-brand-1 outline-none"
                />
              </div>

              <div>
                <label className="block text-xs font-bold text-ink mb-1">Signature Label (English)</label>
                <input
                  type="text"
                  value={settings.cert_footer_sig_en || ""}
                  onChange={(e) => handleChange("cert_footer_sig_en", e.target.value)}
                  className="w-full px-3.5 py-2 rounded-xl text-xs border border-gray-300 focus:border-brand-1 outline-none"
                />
              </div>

              <h2 className="text-lg font-bold text-ink border-b pt-4 pb-2">Sinhala Certificate Texts (සිංහල සහතික පාඨයන්)</h2>

              <div>
                <label className="block text-xs font-bold text-ink mb-1">Header Title (Sinhala)</label>
                <input
                  type="text"
                  value={settings.cert_title_si || ""}
                  onChange={(e) => handleChange("cert_title_si", e.target.value)}
                  className="w-full px-3.5 py-2 rounded-xl text-xs border border-gray-300 focus:border-brand-1 outline-none"
                />
              </div>

              <div>
                <label className="block text-xs font-bold text-ink mb-1">Organization Sub-title (Sinhala)</label>
                <input
                  type="text"
                  value={settings.cert_org_si || ""}
                  onChange={(e) => handleChange("cert_org_si", e.target.value)}
                  className="w-full px-3.5 py-2 rounded-xl text-xs border border-gray-300 focus:border-brand-1 outline-none"
                />
              </div>

              <div>
                <label className="block text-xs font-bold text-ink mb-1">Offered To Phrase (Sinhala)</label>
                <textarea
                  rows={2}
                  value={settings.cert_offered_si || ""}
                  onChange={(e) => handleChange("cert_offered_si", e.target.value)}
                  className="w-full px-3.5 py-2 rounded-xl text-xs border border-gray-300 focus:border-brand-1 outline-none"
                />
              </div>

              <div>
                <label className="block text-xs font-bold text-ink mb-1">Acknowledgment Text (Sinhala)</label>
                <textarea
                  rows={2}
                  value={settings.cert_ack_si || ""}
                  onChange={(e) => handleChange("cert_ack_si", e.target.value)}
                  className="w-full px-3.5 py-2 rounded-xl text-xs border border-gray-300 focus:border-brand-1 outline-none"
                />
              </div>

              <div>
                <label className="block text-xs font-bold text-ink mb-1">Blessings Stanza Paragraph (Sinhala)</label>
                <textarea
                  rows={3}
                  value={settings.cert_blessing_si || ""}
                  onChange={(e) => handleChange("cert_blessing_si", e.target.value)}
                  className="w-full px-3.5 py-2 rounded-xl text-xs border border-gray-300 focus:border-brand-1 outline-none"
                />
              </div>

              <div>
                <label className="block text-xs font-bold text-ink mb-1">Highlight Blessing Box (Sinhala)</label>
                <textarea
                  rows={2}
                  value={settings.cert_stanza_si || ""}
                  onChange={(e) => handleChange("cert_stanza_si", e.target.value)}
                  className="w-full px-3.5 py-2 rounded-xl text-xs border border-gray-300 focus:border-brand-1 outline-none"
                />
              </div>

              <div>
                <label className="block text-xs font-bold text-ink mb-1">Signature Label (Sinhala)</label>
                <input
                  type="text"
                  value={settings.cert_footer_sig_si || ""}
                  onChange={(e) => handleChange("cert_footer_sig_si", e.target.value)}
                  className="w-full px-3.5 py-2 rounded-xl text-xs border border-gray-300 focus:border-brand-1 outline-none"
                />
              </div>
            </div>

            {/* Live Preview Column */}
            <div className="bg-white p-6 rounded-2xl border border-brand-1/10 shadow-sm space-y-4">
              <h2 className="text-lg font-bold text-ink border-b pb-2">Live Certificate Preview</h2>
              <div className="bg-white p-6 rounded-2xl border-4 border-double border-amber-600/60 shadow-lg text-center space-y-4 text-xs">
                <img src="/logo.png" alt="Logo" className="w-16 h-16 object-contain mx-auto" />
                <h3 className="font-black text-xl text-brand-1">{settings.cert_title_en}</h3>
                <p className="font-bold text-amber-900">{settings.cert_org_en}</p>
                <p className="text-gray-600 italic">{settings.cert_offered_en}</p>

                <div className="py-2">
                  <span className="px-4 py-1 rounded-full bg-brand-1 text-white font-bold">
                    Morning Meal (Heel Dana)
                  </span>
                </div>

                <div className="py-2 border-y border-amber-200">
                  <p className="font-black text-brand-1 text-base">Donor Name & Family</p>
                  <p className="text-emerald-800 font-bold mt-1">{settings.cert_ack_en}</p>
                </div>

                <p className="text-gray-700">{settings.cert_blessing_en}</p>

                <div className="p-3 bg-brand-1/5 border border-brand-1/20 rounded-xl font-black text-brand-1">
                  {settings.cert_stanza_en}
                </div>

                <div className="pt-4 flex justify-between items-center text-[10px] text-gray-500 font-bold border-t">
                  <span>Issued Date: 14/08/2026</span>
                  <span>{settings.cert_footer_sig_en}</span>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* TAB 2: REMINDER LETTER TEMPLATE */}
        {activeTab === "letter" && (
          <div className="space-y-4">
            {/* Language Switcher Sub-Bar */}
            <div className="flex items-center gap-2 max-w-md bg-white p-1.5 rounded-2xl border border-brand-1/10 shadow-sm">
              <button
                type="button"
                onClick={() => setLetterFormLang("si")}
                className={`flex-1 py-2.5 px-4 text-xs font-bold rounded-xl transition-all ${
                  letterFormLang === "si"
                    ? "bg-brand-1 text-white shadow-sm"
                    : "text-ink hover:bg-gray-100"
                }`}
              >
                සිංහල ලේඛනය (Sinhala Letter)
              </button>
              <button
                type="button"
                onClick={() => setLetterFormLang("en")}
                className={`flex-1 py-2.5 px-4 text-xs font-bold rounded-xl transition-all ${
                  letterFormLang === "en"
                    ? "bg-brand-1 text-white shadow-sm"
                    : "text-ink hover:bg-gray-100"
                }`}
              >
                English Letter
              </button>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              {/* Form Column */}
              <div className="bg-white p-6 rounded-2xl border border-brand-1/10 shadow-sm space-y-4">
                <h2 className="text-lg font-bold text-ink border-b pb-2">
                  {letterFormLang === "si" ? "ලිපි ශීර්ෂය හා නිලධාරී මණ්ඩල තොරතුරු" : "Letterhead & Contact Info"}
                </h2>

                <div>
                  <label className="block text-sm font-bold text-ink mb-1">
                    {letterFormLang === "si" ? "සංවිධාන නාමය" : "Organization Title"}
                  </label>
                  <input
                    type="text"
                    value={letterFormLang === "si" ? settings.letter_org_title_si || "" : settings.letter_org_title || ""}
                    onChange={(e) => handleChange(letterFormLang === "si" ? "letter_org_title_si" : "letter_org_title", e.target.value)}
                    className="w-full px-4 py-2.5 rounded-xl text-sm font-medium border border-gray-300 focus:border-brand-1 outline-none"
                  />
                </div>

                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="block text-sm font-bold text-ink mb-1">
                      {letterFormLang === "si" ? "අනුශාසක 1" : "Patron 1"}
                    </label>
                    <input
                      type="text"
                      value={letterFormLang === "si" ? settings.letter_patron_1_si || "" : settings.letter_patron_1 || ""}
                      onChange={(e) => handleChange(letterFormLang === "si" ? "letter_patron_1_si" : "letter_patron_1", e.target.value)}
                      className="w-full px-4 py-2.5 rounded-xl text-sm font-medium border border-gray-300 focus:border-brand-1 outline-none"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-bold text-ink mb-1">
                      {letterFormLang === "si" ? "ප්‍රධාන සභාපති" : "Chief President"}
                    </label>
                    <input
                      type="text"
                      value={letterFormLang === "si" ? settings.letter_patron_2_si || "" : settings.letter_patron_2 || ""}
                      onChange={(e) => handleChange(letterFormLang === "si" ? "letter_patron_2_si" : "letter_patron_2", e.target.value)}
                      className="w-full px-4 py-2.5 rounded-xl text-sm font-medium border border-gray-300 focus:border-brand-1 outline-none"
                    />
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="block text-sm font-bold text-ink mb-1">
                      {letterFormLang === "si" ? "ප්‍රධාන ලේකම්" : "Chief Secretary"}
                    </label>
                    <input
                      type="text"
                      value={letterFormLang === "si" ? settings.letter_patron_3_si || "" : settings.letter_patron_3 || ""}
                      onChange={(e) => handleChange(letterFormLang === "si" ? "letter_patron_3_si" : "letter_patron_3", e.target.value)}
                      className="w-full px-4 py-2.5 rounded-xl text-sm font-medium border border-gray-300 focus:border-brand-1 outline-none"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-bold text-ink mb-1">
                      {letterFormLang === "si" ? "භාණ්ඩාගාරික" : "Treasurer"}
                    </label>
                    <input
                      type="text"
                      value={letterFormLang === "si" ? settings.letter_patron_4_si || "" : settings.letter_patron_4 || ""}
                      onChange={(e) => handleChange(letterFormLang === "si" ? "letter_patron_4_si" : "letter_patron_4", e.target.value)}
                      className="w-full px-4 py-2.5 rounded-xl text-sm font-medium border border-gray-300 focus:border-brand-1 outline-none"
                    />
                  </div>
                </div>

                <div>
                  <label className="block text-sm font-bold text-ink mb-1">
                    {letterFormLang === "si" ? "ප්‍රධාන සංවිධායක" : "Chief Organizer"}
                  </label>
                  <input
                    type="text"
                    value={letterFormLang === "si" ? settings.letter_president_si || "" : settings.letter_president || ""}
                    onChange={(e) => handleChange(letterFormLang === "si" ? "letter_president_si" : "letter_president", e.target.value)}
                    className="w-full px-4 py-2.5 rounded-xl text-sm font-medium border border-gray-300 focus:border-brand-1 outline-none"
                  />
                </div>

                <div className="grid grid-cols-3 gap-3">
                  <div>
                    <label className="block text-sm font-bold text-ink mb-1">Phone</label>
                    <input
                      type="text"
                      value={settings.letter_phone || ""}
                      onChange={(e) => handleChange("letter_phone", e.target.value)}
                      className="w-full px-4 py-2.5 rounded-xl text-sm font-medium border border-gray-300 focus:border-brand-1 outline-none"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-bold text-ink mb-1">Whatsapp</label>
                    <input
                      type="text"
                      value={settings.letter_whatsapp || ""}
                      onChange={(e) => handleChange("letter_whatsapp", e.target.value)}
                      className="w-full px-4 py-2.5 rounded-xl text-sm font-medium border border-gray-300 focus:border-brand-1 outline-none"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-bold text-ink mb-1">Email</label>
                    <input
                      type="text"
                      value={settings.letter_email || ""}
                      onChange={(e) => handleChange("letter_email", e.target.value)}
                      className="w-full px-4 py-2.5 rounded-xl text-sm font-medium border border-gray-300 focus:border-brand-1 outline-none"
                    />
                  </div>
                </div>

                <h2 className="text-lg font-bold text-ink border-b pt-4 pb-2">
                  {letterFormLang === "si" ? "ලිපියේ අන්තර්ගතය හා බැංකු තොරතුරු" : "Letter Content & Bank Details"}
                </h2>

                <div>
                  <label className="block text-sm font-bold text-ink mb-1">
                    {letterFormLang === "si" ? "ලිපියේ මාතෘකාව (Subject)" : "Letter Subject Heading"}
                  </label>
                  <input
                    type="text"
                    value={letterFormLang === "si" ? settings.letter_subject_si || "" : settings.letter_subject || ""}
                    onChange={(e) => handleChange(letterFormLang === "si" ? "letter_subject_si" : "letter_subject", e.target.value)}
                    className="w-full px-4 py-2.5 rounded-xl text-sm font-medium border border-gray-300 focus:border-brand-1 outline-none"
                  />
                </div>

                <div>
                  <label className="block text-sm font-bold text-ink mb-1">
                    {letterFormLang === "si" ? "1 වන ඡේදය ({recipient} භාවිත කරන්න)" : "Paragraph 1 (Use {recipient} for donor name)"}
                  </label>
                  <textarea
                    rows={2}
                    value={letterFormLang === "si" ? settings.letter_body_p1_si || "" : settings.letter_body_p1 || ""}
                    onChange={(e) => handleChange(letterFormLang === "si" ? "letter_body_p1_si" : "letter_body_p1", e.target.value)}
                    className="w-full px-4 py-2.5 rounded-xl text-sm font-medium border border-gray-300 focus:border-brand-1 outline-none"
                  />
                </div>

                <div>
                  <label className="block text-sm font-bold text-ink mb-1">
                    {letterFormLang === "si" ? "2 වන ඡේදය ({month}, {day}, {purpose} භාවිත කරන්න)" : "Paragraph 2 (Use {month}, {day}, {purpose})"}
                  </label>
                  <textarea
                    rows={2}
                    value={letterFormLang === "si" ? settings.letter_body_p2_si || "" : settings.letter_body_p2 || ""}
                    onChange={(e) => handleChange(letterFormLang === "si" ? "letter_body_p2_si" : "letter_body_p2", e.target.value)}
                    className="w-full px-4 py-2.5 rounded-xl text-sm font-medium border border-gray-300 focus:border-brand-1 outline-none"
                  />
                </div>

                <div>
                  <label className="block text-sm font-bold text-ink mb-1">
                    {letterFormLang === "si" ? "3 වන ඡේදය ({year}, {meal_type} භාවිත කරන්න)" : "Paragraph 3 (Use {year}, {meal_type})"}
                  </label>
                  <textarea
                    rows={3}
                    value={letterFormLang === "si" ? settings.letter_body_p3_si || "" : settings.letter_body_p3 || ""}
                    onChange={(e) => handleChange(letterFormLang === "si" ? "letter_body_p3_si" : "letter_body_p3", e.target.value)}
                    className="w-full px-4 py-2.5 rounded-xl text-sm font-medium border border-gray-300 focus:border-brand-1 outline-none"
                  />
                </div>

                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="block text-sm font-bold text-ink mb-1">
                      {letterFormLang === "si" ? "බැංකුව හා ශාඛාව" : "Bank Name & Branch"}
                    </label>
                    <input
                      type="text"
                      value={letterFormLang === "si" ? settings.letter_bank_name_si || "" : settings.letter_bank_name || ""}
                      onChange={(e) => handleChange(letterFormLang === "si" ? "letter_bank_name_si" : "letter_bank_name", e.target.value)}
                      className="w-full px-4 py-2.5 rounded-xl text-sm font-medium border border-gray-300 focus:border-brand-1 outline-none"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-bold text-ink mb-1">
                      {letterFormLang === "si" ? "ගිණුම් අංකය" : "Account Number"}
                    </label>
                    <input
                      type="text"
                      value={letterFormLang === "si" ? settings.letter_bank_acc_si || "" : settings.letter_bank_acc || ""}
                      onChange={(e) => handleChange(letterFormLang === "si" ? "letter_bank_acc_si" : "letter_bank_acc", e.target.value)}
                      className="w-full px-4 py-2.5 rounded-xl text-sm font-medium border border-gray-300 focus:border-brand-1 outline-none"
                    />
                  </div>
                </div>

                <div>
                  <label className="block text-sm font-bold text-ink mb-1">
                    {letterFormLang === "si" ? "ගිණුමේ නම" : "Bank Account Owner Name"}
                  </label>
                  <input
                    type="text"
                    value={letterFormLang === "si" ? settings.letter_bank_owner_si || "" : settings.letter_bank_owner || ""}
                    onChange={(e) => handleChange(letterFormLang === "si" ? "letter_bank_owner_si" : "letter_bank_owner", e.target.value)}
                    className="w-full px-4 py-2.5 rounded-xl text-sm font-medium border border-gray-300 focus:border-brand-1 outline-none"
                  />
                </div>
              </div>

              {/* Live Preview Column */}
              <div className="bg-white p-6 rounded-2xl border border-brand-1/10 shadow-sm space-y-4">
                <h2 className="text-lg font-bold text-ink border-b pb-2">
                  {letterFormLang === "si" ? "සජීවී ලිපි පෙරදසුන (Sinhala Live Preview)" : "English Live Letter Preview"}
                </h2>
                <div
                  className="bg-white p-6 rounded-2xl border-2 border-brand-1/30 shadow-md space-y-4 text-sm font-medium"
                  style={letterFormLang === "si" ? { fontFamily: "'Noto Serif Sinhala', 'Abhaya Libre', serif" } : {}}
                >
                  <div className="text-center border-b pb-2">
                    <img src="/logo.png" alt="Logo" className="w-14 h-14 object-contain mx-auto mb-1" />
                    <h3 className="font-bold text-lg text-brand-1">
                      {letterFormLang === "si" ? settings.letter_org_title_si : settings.letter_org_title}
                    </h3>
                    <p className="text-xs text-gray-700 mt-1 font-bold">
                      {letterFormLang === "si" ? settings.letter_patron_1_si : settings.letter_patron_1}
                    </p>
                  </div>

                  <div className="text-center font-bold text-base text-brand-1 border-b pb-1">
                    {letterFormLang === "si" ? settings.letter_subject_si : settings.letter_subject}
                  </div>

                  <p className="text-gray-800 leading-relaxed text-sm">
                    {renderHighlightedText(
                      letterFormLang === "si"
                        ? (settings.letter_body_p1_si || "කන්දෙගම ඓතිහාසික ධනංජය රජමහා විහාරස්ථ සාගරමති පිරිවෙනේ නේවාසික මහා සංඝරත්නයේ සිව්පසය උදෙසා {recipient} විසින් ඉදිරිපත්ව දායකත්වය ලබාදීම පිළිබඳව අපගේ ප්‍රණාමය පුද කරමු.")
                        : (settings.letter_body_p1 || "We express our gratitude to {recipient} for sponsoring."),
                      { recipient: letterFormLang === "si" ? "සුනිල් පෙරේරා මහතා" : "Mr. Sunil Perera" }
                    )}
                  </p>

                  <p className="text-gray-800 leading-relaxed text-sm">
                    {renderHighlightedText(
                      letterFormLang === "si"
                        ? (settings.letter_body_p2_si || "ඒ අනුව, සෑම වසරකම {month} මස {day} වන දින \"{purpose}\" සඳහා වන දානමය දායකත්වය {recipient_possessive} නමින් වෙන් කර ඇති බව කාරුණිකව මතක් කර සිටිමු.")
                        : (settings.letter_body_p2 || "Every year on {month} {day}, {purpose} is reserved."),
                      {
                        month: letterFormLang === "si" ? "මාර්තු" : "March",
                        day: letterFormLang === "si" ? "15 වන දින" : "15",
                        purpose: letterFormLang === "si" ? "වාර්ෂික පින්කම" : "Annual Blessing",
                        recipient_possessive: letterFormLang === "si" ? "ඔබතුමන්ලාගේ" : "your",
                        recipient: letterFormLang === "si" ? "සුනිල් පෙරේරා මහතා" : "Mr. Sunil Perera"
                      }
                    )}
                  </p>

                  <div className="p-4 bg-brand-1/5 rounded-xl border border-brand-1/15 space-y-1 font-bold text-sm">
                    <p className="text-brand-1 text-base">{letterFormLang === "si" ? settings.letter_bank_name_si : settings.letter_bank_name}</p>
                    <p>Acc No: {letterFormLang === "si" ? settings.letter_bank_acc_si : settings.letter_bank_acc}</p>
                    <p>Owner: {letterFormLang === "si" ? settings.letter_bank_owner_si : settings.letter_bank_owner}</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}

        <div className="flex justify-end pt-4">
          <button
            type="submit"
            disabled={saving}
            className="px-8 py-3.5 bg-emerald-700 hover:bg-emerald-800 text-white font-bold text-sm rounded-xl shadow-lg transition-all active:scale-95 disabled:opacity-50"
          >
            {saving ? "Saving Templates..." : "Save All Templates"}
          </button>
        </div>
      </form>
    </div>
  );
};
